#!/usr/bin/env python3
"""Post-build: patches Python wheel with Pythonic sugar."""
import re, sys, zipfile, tempfile
from pathlib import Path


def get_patch_code():
    """Return the patch code as a string. Avoids triple-quote nesting."""
    lines = []
    a = lines.append

    a("")
    a("# === STRANDS PYTHONIC SUGAR ===")
    a("")
    a("_OrigAgent = StrandsAgent")
    a("class Agent(_OrigAgent):")
    a("    'Pythonic Agent wrapper.'")
    a("    def __new__(cls, *a, **kw): return _OrigAgent.__new__(cls)")
    a("    def __init__(self, *a, **kw):")
    a("        if a and isinstance(a[0], AgentConfig): super().__init__(a[0])")
    a("        else: super().__init__(AgentConfig(**kw))")
    a("    def __call__(self, prompt): return self.invoke(prompt)")
    a("")
    a("_OrigBedrock = BedrockModelProvider")
    a("class Bedrock(_OrigBedrock):")
    a("    'Bedrock(**kw) shorthand.'")
    a("    def __init__(self, **kw): super().__init__(BedrockModelConfig(**kw))")
    a("")
    a("_OrigAnthropic = AnthropicModelProvider")
    a("class Anthropic(_OrigAnthropic):")
    a("    'Anthropic(**kw) shorthand.'")
    a("    def __init__(self, **kw): super().__init__(AnthropicModelConfig(**kw))")
    a("")
    a("_OrigOpenAI = OpenAIModelProvider")
    a("class OpenAI(_OrigOpenAI):")
    a("    'OpenAI(**kw) shorthand.'")
    a("    def __init__(self, **kw): super().__init__(OpenAIModelConfig(**kw))")
    a("")
    a("_OrigGemini = GeminiModelProvider")
    a("class Gemini(_OrigGemini):")
    a("    'Gemini(**kw) shorthand.'")
    a("    def __init__(self, **kw): super().__init__(GeminiModelConfig(**kw))")
    a("")
    a("# -- agent.tool.X() proxy --")
    a("class _ToolCallerProxy:")
    a("    __slots__ = ('_agent',)")
    a("    def __init__(self, agent): object.__setattr__(self, '_agent', agent)")
    a("    def __getattr__(self, name):")
    a("        agent = object.__getattribute__(self, '_agent')")
    a("        reg = agent.tool_registry")
    a("        if not reg.has(name) and '_' in name:")
    a("            alt = name.replace('_', '-')")
    a("            if reg.has(alt): name = alt")
    a("        if not reg.has(name): raise AttributeError(f\"Tool '{name}' not found\")")
    a("        td = reg.get(name)")
    a("        _n = name")
    a("        def caller(**kw):")
    a("            import json as _j")
    a("            ij = _j.dumps(kw, default=str)")
    a("            raw = td.execute(ij)")
    a("            agent.call_tool(_n, ij)")
    a("            try: return _j.loads(raw)")
    a("            except: return raw")
    a("        return caller")
    a("")
    a("Agent.tool = property(lambda self: _ToolCallerProxy(self))")
    a("")
    a("# -- @tool decorator --")
    a("import inspect as _inspect, json as _json, typing as _typing, functools as _functools")
    a("_TM = {str:'string',int:'number',float:'number',bool:'boolean',list:'array',dict:'object'}")
    a("")
    a("class _FTH(ToolHandler):")
    a("    def __init__(self, f): super().__init__(); self._f = f")
    a("    def handle(self, ij):")
    a("        p = _json.loads(ij); s = _inspect.signature(self._f)")
    a("        b = {k:v for k,v in p.items() if k in s.parameters}; r = self._f(**b)")
    a("        if isinstance(r, str):")
    a("            try:")
    a("                x = _json.loads(r)")
    a("                if isinstance(x, (dict, list)): return r")
    a("            except: pass")
    a("            return _json.dumps({'result': r})")
    a("        if isinstance(r, dict): return _json.dumps(r, default=str)")
    a("        return _json.dumps({'result': r}, default=str)")
    a("")
    a("def _bs(func):")
    a("    s = _inspect.signature(func)")
    a("    h = _typing.get_type_hints(func) if hasattr(func,'__annotations__') else {}")
    a("    ps, rq = {}, []")
    a("    for pn, p in s.parameters.items():")
    a("        if pn in ('self','cls','tool_use_id','agent','kwargs'): continue")
    a("        pt = h.get(pn, str); o = getattr(pt,'__origin__',None); op = False")
    a("        if o is _typing.Union:")
    a("            a = pt.__args__; nn = [x for x in a if x is not type(None)]")
    a("            if len(nn)==1: pt,op = nn[0],True")
    a("        ps[pn] = {'type': _TM.get(pt,'string'), 'description': pn.replace('_',' ')}")
    a("        if p.default is _inspect.Parameter.empty and not op: rq.append(pn)")
    a("    sc = {'type':'object','properties':ps}")
    a("    if rq: sc['required'] = rq")
    a("    return _json.dumps(sc)")
    a("")
    a("def tool(func=None, *, name=None, description=None):")
    a("    'Decorator to turn a Python function into an agent tool.'")
    a("    def dec(fn):")
    a("        tn = name or fn.__name__; d = (fn.__doc__ or '').strip()")
    a("        fl = d.split(chr(10))[0] if d else ''; td = description or fl or ('Tool: '+tn)")
    a("        ft = FunctionTool(tn, td, _bs(fn), _FTH(fn))")
    a("        _functools.update_wrapper(ft, fn); ft._original_func = fn; return ft")
    a("    return dec(func) if func else dec")
    a("")
    a("# -- use_library: universal dynamic tool factory --")
    a("import importlib as _importlib, pkgutil as _pkgutil")
    a("")
    a("def _lib_import(lib, path):")
    a("    if not path or path == lib: return _importlib.import_module(lib)")
    a("    full = f'{lib}.{path}' if not path.startswith(f'{lib}.') else path")
    a("    try: return _importlib.import_module(full)")
    a("    except ImportError: pass")
    a("    parts = full.rsplit('.', 1)")
    a("    if len(parts) == 2:")
    a("        try:")
    a("            mod = _importlib.import_module(parts[0])")
    a("            return getattr(mod, parts[1])")
    a("        except (ImportError, AttributeError): pass")
    a("    segs = full.split('.')")
    a("    for i in range(len(segs), 0, -1):")
    a("        try:")
    a("            mod = _importlib.import_module('.'.join(segs[:i]))")
    a("            obj = mod")
    a("            for attr in segs[i:]: obj = getattr(obj, attr)")
    a("            return obj")
    a("        except (ImportError, AttributeError): continue")
    a("    raise ImportError(f'Cannot resolve {path!r} in {lib}')")
    a("")
    a("def _lib_discover(lib):")
    a("    try: m = _importlib.import_module(lib)")
    a("    except ImportError: return {'error': f'{lib} not installed. pip install {lib}'}")
    a("    pkgs, mods = [], []")
    a("    if hasattr(m, '__path__'):")
    a("        for _, n, ispkg in _pkgutil.iter_modules(m.__path__):")
    a("            if not n.startswith('_'): (pkgs if ispkg else mods).append(n)")
    a("    pub = [n for n in dir(m) if not n.startswith('_')][:30]")
    a("    return {'packages': pkgs, 'modules': mods, 'public': pub}")
    a("")
    a("def _lib_describe(obj):")
    a("    info = {'type': type(obj).__name__, 'name': getattr(obj, '__name__', str(obj))}")
    a("    if _inspect.isclass(obj):")
    a("        info['methods'] = [m for m in dir(obj) if not m.startswith('_') and callable(getattr(obj, m, None))][:30]")
    a("        try:")
    a("            sig = _inspect.signature(obj.__init__)")
    a("            info['init_params'] = [p for p in sig.parameters if p != 'self']")
    a("        except: pass")
    a("        if obj.__doc__: info['doc'] = obj.__doc__[:500]")
    a("    elif callable(obj):")
    a("        try:")
    a("            sig = _inspect.signature(obj)")
    a("            info['params'] = {n: {'default': str(p.default) if p.default is not _inspect.Parameter.empty else 'REQUIRED'} for n, p in sig.parameters.items()}")
    a("        except: pass")
    a("        if obj.__doc__: info['doc'] = obj.__doc__[:500]")
    a("    elif _inspect.ismodule(obj):")
    a("        info['public'] = [n for n in dir(obj) if not n.startswith('_')][:30]")
    a("        if obj.__doc__: info['doc'] = obj.__doc__[:300]")
    a("    else:")
    a("        info['value'] = str(obj)[:200]")
    a("    return info")
    a("")
    a("def _lib_serialize(r):")
    a("    if r is None: return 'None'")
    a("    if isinstance(r, (str,int,float,bool)): return str(r)")
    a("    if isinstance(r, (list,tuple)): return _json.dumps([str(x)[:200] for x in r[:50]])")
    a("    if isinstance(r, dict):")
    a("        safe = {}")
    a("        for k,v in list(r.items())[:50]:")
    a("            try: _json.dumps(v); safe[str(k)] = v")
    a("            except: safe[str(k)] = str(v)[:200]")
    a("        return _json.dumps(safe, default=str)")
    a("    return _json.dumps(_lib_describe(r), default=str)")
    a("")
    a("def use_library(library_name, module='__discovery__', method='', parameters=None, label=''):")
    a("    'Universal library access - discover, inspect, call any API in any installed package.'")
    a("    params = parameters or {}")
    a("    try:")
    a("        if module == '__discovery__':")
    a("            info = _lib_discover(library_name)")
    a("            if 'error' in info: return {'status': 'error', 'content': [{'text': info['error']}]}")
    a("            return {'status': 'success', 'content': [{'text': _json.dumps(info, indent=2)}]}")
    a("        target = _lib_import(library_name, module)")
    a("        if method == '__describe__':")
    a("            return {'status': 'success', 'content': [{'text': _json.dumps(_lib_describe(target), indent=2, default=str)}]}")
    a("        if method:")
    a("            if not hasattr(target, method):")
    a("                avail = [a for a in dir(target) if not a.startswith('_')][:20]")
    a("                return {'status': 'error', 'content': [{'text': f\"'{method}' not found. Available: {avail}\"}]}")
    a("            target = getattr(target, method)")
    a("        if not callable(target):")
    a("            return {'status': 'success', 'content': [{'text': f'{module}.{method} = {_lib_serialize(target)}'}]}")
    a("        result = target(**params)")
    a("        return {'status': 'success', 'content': [{'text': f'{library_name}.{module}.{method}() -> {_lib_serialize(result)[:3000]}'}]}")
    a("    except ImportError as e:")
    a("        return {'status': 'error', 'content': [{'text': f'Import error: {e}'}]}")
    a("    except TypeError as e:")
    a("        try:")
    a("            sig = _inspect.signature(target)")
    a("            return {'status': 'error', 'content': [{'text': f'TypeError: {e} -- Expected: {sig}'}]}")
    a("        except: return {'status': 'error', 'content': [{'text': f'TypeError: {e}'}]}")
    a("    except Exception as e:")
    a("        return {'status': 'error', 'content': [{'text': f'{type(e).__name__}: {e}'}]}")
    a("")
    a("def make_use_tool(library_name, description=''):")
    a("    'Create a use_X tool for any Python package.'")
    a("    desc = description or f'Universal {library_name} access'")
    a("    @tool(name=f'use_{library_name}', description=f'{desc} - discover, inspect, call any {library_name} API.')")
    a("    def _use(module='__discovery__', method='', parameters=None, label=''):")
    a("        return use_library(library_name, module, method, parameters, label)")
    a("    return _use")
    a("")

    return "\n".join(lines)


def patch(dd="dist/python"):
    ws = list(Path(dd).glob("*.whl"))
    if not ws:
        sys.exit("No wheel")
    wp = ws[0]
    print(f"Patching {wp}")
    with tempfile.TemporaryDirectory() as t:
        with zipfile.ZipFile(wp, "r") as z:
            z.extractall(t)
        ip = list(Path(t).rglob("strands_jsii/__init__.py"))[0]
        c = ip.read_text()
        if "STRANDS PYTHONIC SUGAR" in c:
            print("Already patched")
            return
        c = re.sub(
            r'(__all__\s*=\s*\[)',
            r'\1\n    "Agent",\n    "Bedrock",\n    "Anthropic",\n    "OpenAI",\n    "Gemini",\n    "tool",\n    "make_use_tool",\n    "use_library",',
            c,
            count=1,
        )
        patch_code = get_patch_code()
        c = c.replace("publication.publish()", patch_code + "\npublication.publish()", 1)
        ip.write_text(c)
        wp.unlink()
        with zipfile.ZipFile(wp, "w", zipfile.ZIP_DEFLATED) as z:
            for f in Path(t).rglob("*"):
                if f.is_file():
                    z.write(f, f.relative_to(t))
    print("OK patched")


if __name__ == "__main__":
    patch(sys.argv[1] if len(sys.argv) > 1 else "dist/python")
